name: Enviar Issue para o Trello

on:
  issues:
    types: [opened]

jobs:
  create_trello_card:
    runs-on: ubuntu-latest
    steps:
      - name: Criar cartao no Trello via API
        run: |
          curl --request POST \
            --url "https://api.trello.com/1/cards" \
            --header "Accept: application/json" \
            --data-urlencode "key=${{ secrets.TRELLO_KEY }}" \
            --data-urlencode "token=${{ secrets.TRELLO_TOKEN }}" \
            --data-urlencode "idList=${{ secrets.TRELLO_LIST_ID }}" \
            --data-urlencode "name=${{ github.event.issue.title }}" \
            --data-urlencode "desc=Link direto para o GitHub: ${{ github.event.issue.html_url }}"
